# fly.toml app configuration file generated for grain-nginx on 2025-06-01T22:28:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grain-nginx'
primary_region = 'sea'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
